### ISSUE TITLE
Don't output `nvm install` suggestion if nvm isn't installed

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [parshap/check-node-version#19]
This is actually a little difficult because you'd have to determine whether `nvm` is installed in an OS-independent manner. Best route would probably be to write a new `is-nvm-installed` package and use it here.

**Comment by rasenplanscher** [comment]
I think, we can just add `nvm` to the available programs here and then query that.

@parshap 
Do you see `nvm` in scope for `check-node-version`?

**Comment by parshap** [comment]
I’m ok with that, yes. I think it’d be useful to even support checking versions of arbitrary npm packages (by reading node_modules/:package/package.json). It’s a bit a stretch in terms of scope of the package and especially the name of the package, but I think a kitchen sink sort of utility package makes sense here as the use cases are highly related and likely to be used together.

**Comment by rasenplanscher** [comment]
> I think it’d be useful to even support checking versions of arbitrary npm packages (by reading node_modules/:package/package.json)

I briefly thought of checking local versions (`npm` etc. in my case) in relation to #12. `package.json` already defines the required versions and double-checking those would only tell us that an `npm i` is required. Would that be the target? What would be the interface? Should all packages be checked or only selected ones? Should `package-lock.json` be verified, rather than just `package.json`?

**Comment by rasenplanscher** [comment]
One issue we face here is that `nvm` does not work on Windows, so we should support `nvm-windows` there. However, they must have different versions. I feel that we should have some mechanism in place so that a requirement for `nvm` on Windows or `nvm-windows` on Mac/Linux should not lead to an error but just a note like with `notfound` for `--print`. I'm not sure about the best way to do that, however, because it seems like a lot of case-coding 🤔

**Comment by parshap** [comment]
To address the original issue of improving the printed install instructions, I think a simple `which nvm` will suffice. More full fledged support for nvm is probably not high in demand.

**Comment by rasenplanscher** [comment]
I agree, just need to make it cross-platform, but that's not too hard 🙂
