### ISSUE TITLE
Consider converting to TypeScript

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [parshap/check-node-version#24]
The only guaranteed way to keep `.d.ts` typings up-to-date from the source is to convert to TypeScript. I'd be very willing to send in a PR!

**Comment by parshap** [comment]
@JoshuaKGoldberg, would you be interested in taking over as the primary maintainer? If so, then I would be open to the TypeScript conversion. Otherwise I would like to keep the barrier to entry as low as possible so myself and others are able to make changes and fixes without getting familiar with TypeScript and the tooling around it.

**Comment by JoshuaKGoldberg** [comment]
Ehh, I can't make that commitment :( this is small enough that it seems reasonable to keep in JS.
