### ISSUE TITLE
Suggest using version from .nvmrc if present

### ISSUE THREAD

**Issue by blowery** [parshap/check-node-version#26]
When using `--package`, the requested version in `engines` may not be compatible with `nvm`. For instance, `engines: ^10.5.0` when run with node 10.1 will output `To install node, run nvm install ^10.5.0 or see https://nodejs.org/`. That nvm command doesn't actually work.

Instead, if there's a `.nvmrc` is present, suggest using `nvm i` without the version specifier.

**Comment by rasenplanscher** [comment]
I see two separate goals here:
1. Modify version strings for output so that the given instruction will work as printed. Two alternatives:
  a. Modify the version string to have the intended result, as in getting the newest version that satisfies the original specification. 
  b. strip any additional characters, so that `^10.5.0` would yield `nvm install 10.5.0`
2. Check for `.nvmrc` and, if present, print `nvm i` without the version specifier.

Part 1a would require some research into each package's idiosyncracies.
Part 1b would be a lot simpler but not yield the newest fitting version.

Part 2 has the additional complication that [nvm-windows](https://github.com/coreybutler/nvm-windows/) does not support `.nvmrc`.

Personally, I gravitate toward implementing 1b and leaving it at that. Outputting invalid instructions is an actual problem. The rest would be nice to have but to me not worth the effort.

@parshap Are you cool with that?

@blowery If you feel 1a and 2 to be important, your input would be appreciated. I'd be willing to provide an implementation if you can provide clear specifications. They should include any required nvm version as well, since stuff potentially hasn't worked equally for all versions.

**Comment by parshap** [comment]
Good breakdown @rasenplanscher. Your suggestion sounds good to me.
